In [27]:
#Defining the suduku matrix
import numpy as np

#Defining the matrix as sudoku with zero values as empty cells
matrix = np.matrix([[1,0,7,6,0,0,0,0,0],[0,0,9,0,4,0,7,0,0],[0,0,5,0,8,0,0,3,0],[0,2,0,0,0,0,0,8,7],[0,0,4,7,0,6,9,0,0],[7,5,0,0,0,0,0,1,0],[0,4,0,0,9,0,3,0,0],[0,0,1,0,6,0,8,0,0],[0,0,0,0,0,3,1,0,6]])

In [24]:
#Find the index of value 0

matrix2 = matrix.copy()

In [29]:
matrix_previous_state = matrix+1
#Where function returns the index of the cells with row index in 1st tuple and column index in 2nd tuple
#index_of_zeros is tuple of 2 arrays

def current_index_of_zeros():
    return np.where(matrix == 0)


#pull_index function pulls the 'i'th index from index_of_zeros and returns the respective index

def pull_index(i,current_index_of_zero_list):
    #arugment i depends on the number of zeros in the matrix
    ##print('Number of zeros ',len(current_index_of_zero_list[0]))
    return current_index_of_zero_list[0][i],current_index_of_zero_list[1][i]

def possible_valuesof_cell(r,c):
    # r --> row and c --> column
    #find the list of values in 1..9 which pass the basic test
    #The test is for one cell and return a list of possible values
    temp_list = []
    if (matrix[[r],[c]] != 0):
        return [np.NaN]
    for j in range(1,10):  
            #if j is not in the column and row and the box where the cell is present j will be added to the temp_list
            if (j not in matrix[r] and j not in matrix.T[c]):
                temp_row,temp_col = 3*int(r/3),3*int(c/3)
                box_x = []
                box_y = []
                for x in range(3):
                    for y in range(3):
                        #usage of modules function is to reduce the computation 
                        #since already using the first check we checked in the row and column of the cell
                        #Here the cells in the subgrid other the checked cell are checked
                        box_x.append(temp_row + (r+x)%3)
                        box_y.append(temp_col + (c+y)%3)
                box = (box_x,box_y)
                if (j not in matrix[box]):
                    temp_list.append(j)
    return temp_list


def filtr(r,c):
    if(np.isnan(possible_valuesof_cell(r,c))[0] == False):
        count = 0
        temp_lst = []
        temp_row,temp_col = 3*int(r/3),3*int(c/3)
        for l in range(temp_row,temp_row+3):
            for m in range(temp_col,temp_col+3):
                if(np.isnan(possible_valuesof_cell(l,m))[0]):
                    temp_lst = temp_lst+ matrix[[l],[m]].tolist()
                else:
                    temp_lst = temp_lst+[possible_valuesof_cell(l,m)]
       ## print(temp_lst)
        for val in range(1,10):
            for n in range(len(temp_lst)):
                if (val not in temp_lst[n] and temp_lst[n] != possible_valuesof_cell(r,c)):
                        count = count+1
          ##  print(val,",",count)
            if(count == len(temp_lst)-1):
                return [val]
            count = 0
    return possible_valuesof_cell(r,c)
                
#Main picture
c=0
while(np.all(matrix == matrix_previous_state) == False):
    c = c+1
   ## print('loop_count ',c)
    matrix_previous_state = matrix.copy()
    current_index_of_zero_list = current_index_of_zeros()
    lenth_of_zeros = len(current_index_of_zero_list[0])
    for i in range(lenth_of_zeros):
        ##print('ith zero',i)
        row,col = pull_index(i,current_index_of_zero_list)
        if( len(possible_valuesof_cell(row,col))==1):
            matrix[[row],[col]] = possible_valuesof_cell(row,col)[0]

        elif( len(filtr(row,col))==1):
            matrix[[row],[col]] = filtr(row,col)[0]
        ##print(row,',',col,',',possible_valuesof_cell(row,col),',',filtr(row,col))
matrix

matrix([[1, 0, 7, 6, 0, 0, 0, 0, 0],
        [2, 0, 9, 0, 4, 0, 7, 6, 0],
        [4, 6, 5, 0, 8, 7, 2, 3, 0],
        [9, 2, 0, 0, 0, 0, 0, 8, 7],
        [8, 1, 4, 7, 0, 6, 9, 0, 0],
        [7, 5, 0, 0, 0, 0, 0, 1, 0],
        [6, 4, 0, 0, 9, 0, 3, 7, 0],
        [3, 7, 1, 0, 6, 0, 8, 0, 0],
        [5, 9, 0, 0, 7, 3, 1, 0, 6]])

In [9]:
pull_index(13,current_index_of_zero_list)

Number of zeros  53


(2, 1)

In [19]:
np.all(matrix == matrix_previous_state)

True

In [21]:
matrix_previous_state

matrix([[1, 0, 7, 6, 0, 0, 0, 0, 0],
        [2, 0, 9, 0, 4, 0, 7, 6, 0],
        [4, 6, 5, 0, 8, 7, 2, 3, 0],
        [9, 2, 0, 0, 0, 0, 0, 8, 7],
        [0, 1, 4, 7, 0, 6, 9, 0, 0],
        [7, 5, 0, 0, 0, 0, 0, 1, 0],
        [0, 4, 0, 0, 9, 0, 3, 0, 0],
        [0, 7, 1, 0, 6, 0, 8, 0, 0],
        [0, 9, 0, 0, 7, 3, 1, 0, 6]])

In [6]:
ma = []
for i in range(9):
    ma.append([])
ma = [ma]
ma = ma*9
ma = np.array(ma)
ma[2][2]= [1]
ma[2][2]=1
matrix2[[1],[2]]=3
matrix2[[1],[2]]==3

matrix([[ True]])